main:         'dev.metanoia.smartitemsort.griefdefender.SmartItemSortGriefDefender'
name:         'SmartItemSort-GD'
version:      '1.0.0'
author:       'BornToCode'
website:      'https://www.spigotmc.org/resources/smartitemsort-griefdefender.104646/'
api-version:  '1.16'
depend:       ['GriefDefender', 'SmartItemSort']
load:         'POSTWORLD'

description: |
  Enforces GriefDefender claim protections on the item teleports that SmartItemSort performs.

